### ISSUE TITLE
sitecustomize.py is included in pip installation and causes trouble

### ISSUE THREAD

**Issue by DrMeers** [Alir3z4/html2text#184]
So when I have `html2text` in my pip requirements, `lib/python2.7/site.py` tries to import `sitecustomize` and grabs it from `src/html2text/sitecustomize.py` which blows up trying to read `.coveragerc` from the current working directory. The `sitecustomize.py` in the module is specific for running the tests from the repository root and should not affect installations. I was going to exclude it from `MANIFEST.in` however discovered that the tests are intentionally included there, so am not sure what the best solution for this is?

**Comment by Alir3z4** [comment]
I think it makes sense to exclude the tests and all the related files to tests from the distribution package.

**Comment by DrMeers** [comment]
I think the `sitecustomize.py` problem only occurs if you use a `-e` (editable) pip installation. If I remove the `-e` from my `requirements.txt` the issue is resolved. Maybe this issue is invalid...

**Comment by Alir3z4** [comment]
Thanks for updating and clarifying the issue.
I'm still not sure if shipping tests would be helpful.
